module UniversityList
  extend ActiveSupport::Concern
    UNIVERSITIES = [
      "Aberystwyth University",
      "Académie d'Aix-Marseille",
      "Académie d'Orléans-Tours",
      "Académie de Besançon",
      "Académie de Bordeaux",
      "Académie de Créteil",
      "Académie de Mayotte",
      "Académie de Paris",
      "AgroParisTech",
      "AgroSup Dijon",
      "American Graduate School in Paris",
      "American InterContinental University - London",
      "American University of Paris",
      "Anglia Ruskin University",
      "Arizona State University",
      "Aston University",
      "Audencia",
      "Barcelona Graduate School of Economics",
      "Bath Spa University",
      "Bircham International University",
      "Birkbeck College, University of London",
      "Birmingham City University",
      "Boston University",
      "Bournemouth University",
      "British College of Osteopathic Medicine",
      "British Institute in Paris, University of London",
      "Brown University",
      "Brunel University Uxbridge",
      "Buckinghamshire New University",
      "California Institute of Technology",
      "Camberwell College of Arts",
      "Campus Saint Marc",
      "Canterbury Christ Church University",
      "Cardiff University",
      "Cardiff and Vale College",
      "Carnegie Mellon University",
      "Case Western Reserve University",
      "Central Saint Martins College of Art & Design",
      "Centre National d'Etudes Agronomiques des Régions Chaudes",
      "Centre d'Etudes Supérieures Industrielles Paris",
      "Centre d'Etudes Supérieures des Techniques Industrielles",
      "Centre de Formation et de Perfectionnement des Journalistes",
      "Centro Universitario Villanueva",
      "Chelsea College of Art and Design",
      "Christelijke Hogeschool Windesheim",
      "City University",
      "Collège de France",
      "Columbia University",
      "Conservatoire National des Arts et Métiers",
      "Cornell University",
      "Courtauld Institute of Art, University of London",
      "Coventry University",
      "Cranfield University",
      "DUT MMI - Université Bordeaux Montaigne",
      "Dartmouth College",
      "De Haagse Hogeschool",
      "De Montfort University Leicester",
      "Delft University of Technology",
      "Duke University",
      "Dutch Delta University",
      "ENAE Business School",
      "ENIC Telecom Lille 1",
      "EPF Ecole d'Ingénieurs",
      "ESADE Business & Law School",
      "Eada Business School Barcelona",
      "East Coast College",
      "Ecole Catholique d'Arts & Metiers",
      "Ecole Centrale d'Electronique - ECE",
      "Ecole Centrale de Lille",
      "Ecole Centrale de Lyon",
      "Ecole Centrale de Marseille",
      "Ecole Centrale de Nantes",
      "Ecole Européen des Affaires",
      "Ecole Européenne de Chimie, Polymères et Matériaux de Strasbourg",
      "Ecole Française d'Electronique et d'Informatique",
      "Ecole Française de Papeterie et des Industries Graphiques",
      "Ecole Nationale Supérieur d'Ingénieurs de Constructions Aéronautique",
      "Ecole Nationale Supérieur de Géologie de Nancy",
      "Ecole Nationale Supérieur de Mécanique et d'Aéronautique",
      "Ecole Nationale Supérieur de Mécaniques et des Microtechniques",
      "Ecole Nationale Supérieur des Ingénieur des Etudes et Techniques d'Armement",
      "Ecole Nationale Supérieure d'Arts et Métiers de Paris",
      "Ecole Nationale Supérieure d'Electronique et de Radioelectricite de Bordeaux",
      "Ecole Nationale Supérieure de Physique de Marseille",
      "Ecole Nationale Supérieure de Physique de Strasbourg",
      "Ecole Nationale Supérieure de Techniques Avancées",
      "Ecole Nationale Supérieure de l'Aéronautique et de l'Espace",
      "Ecole Nationale Supérieure de l'Electronique et de ses Applications",
      "Ecole Nationale Supérieure des Telecommunications de Bretagne",
      "Ecole Nationale Supérieure des Telecommunications de Paris",
      "Ecole Nationale Supérieure du Pétrole et des Monteurs",
      "Ecole Nationale Supérieure en Electrotechnique, Electronique, Informatique et Hydraulique de Toulouse",
      "Ecole Nationale Vétérinaire d'Alfort",
      "Ecole Nationale Vétérinaire de Lyon",
      "Ecole Nationale Vétérinaire de Nantes",
      "Ecole Nationale Vétérinaire de Toulouse",
      "Ecole Nationale d'Administration",
      "Ecole Nationale d'Ingénieurs de Metz",
      "Ecole Nationale d'Ingénieurs de Saint-Etienne",
      "Ecole Nationale d'Ingénieurs de Tarbes",
      "Ecole Nationale d'Ingénieurs des Techniques des Industries Agricoles et Alimentaires",
      "Ecole Nationale d'Ingénieurs des Travaux Agricoles de Bordeaux",
      "Ecole Nationale d'Ingénieurs des Travaux Agricoles de Clermont-Ferrand",
      "Ecole Nationale de l'Aviation Civile",
      "Ecole Nationale de la Météorologie",
      "Ecole Nationale de la Statistique et de l'Administration Economique",
      "Ecole Nationale de la Statistique et de l'Analyse de l'information",
      "Ecole Nationale des Ponts et Chausees",
      "Ecole Nationale des Sciences Géographiques",
      "Ecole Nationale des Travaux Publics de l'Etat",
      "Ecole Nationale du Génie de l'Eau et de l'Environnement de Strasbourg",
      "Ecole Normale Supérieure de Cachan",
      "Ecole Normale Supérieure de Fontenay-Saint Cloud",
      "Ecole Normale Supérieure de Lyon",
      "Ecole Normale Supérieure de Paris",
      "Ecole Polytechnique Marseille",
      "Ecole Polytechnique Universitaire de Lille",
      "Ecole Pour l'Informatique et les Techniques Avancees",
      "Ecole Spéciale de Mécanique et d'Electricité",
      "Ecole Spéciale des Travaux Publics du Bâtiment et de l'Industrie",
      "Ecole Superieur d'Ingenieurs Leonard de Vinci",
      "Ecole Superieure Robert de Sorbon",
      "Ecole Supérieure Internationale d'Administration des Entreprises",
      "Ecole Supérieure d'Agriculture d'Angers",
      "Ecole Supérieure d'Agriculture de Purpan",
      "Ecole Supérieure d'Electricité",
      "Ecole Supérieure d'Electronique de l'Ouest",
      "Ecole Supérieure d'Informatique-Electronique-Automatique",
      "Ecole Supérieure d'Ingénieurs de Marseille",
      "Ecole Supérieure d'Ingénieurs en Electronique et Electrotechnique",
      "Ecole Supérieure d'Ingénieurs en Génie Electrique",
      "Ecole Supérieure d'Ingénieurs et de Techniciens pour l'Agriculture",
      "Ecole Supérieure d'Optique",
      "Ecole Supérieure de Chimie Organique et Minérale",
      "Ecole Supérieure de Chimie Physique Electronique de Lyon",
      "Ecole Supérieure de Commerce de Bordeaux",
      "Ecole Supérieure de Commerce de Brest",
      "Ecole Supérieure de Commerce de Clermont-Ferrand",
      "Ecole Supérieure de Commerce de Dijon",
      "Ecole Supérieure de Commerce de Le Havre/Caen",
      "Ecole Supérieure de Commerce de Lille",
      "Ecole Supérieure de Commerce de Lyon",
      "Ecole Supérieure de Commerce de Marseille-Provence",
      "Ecole Supérieure de Commerce de Nantes-Atlantique",
      "Ecole Supérieure de Commerce de Paris",
      "Ecole Supérieure de Commerce de Pau",
      "Ecole Supérieure de Commerce de Reims",
      "Ecole Supérieure de Commerce de Rouen",
      "Ecole Supérieure de Commerce de Sophia Antipolis",
      "Ecole Supérieure de Commerce de Toulouse",
      "Ecole Supérieure de Commerce et Management",
      "Ecole Supérieure de Physique et de Chimie Industrielles",
      "Ecole Supérieure des Sciences Commerciales d'Angers",
      "Ecole Supérieure des Sciences Economiques et Commerciales",
      "Ecole Supérieure des Sciences et Technologie de l'Ingénieur de Nancy",
      "Ecole Universitaire d'Ingénieurs de Lille",
      "Ecole d'Architecture de Nancy",
      "Ecole d'Ingénieurs en Informatique pour l'Industrie",
      "Ecole de l'Air",
      "Ecole des Hautes Etudes Commerciales du Nord",
      "Ecole des Hautes Etudes Industrielles de Lille",
      "Ecole des Ingénieurs de la Ville de Paris",
      "Ecole des technologies numeriques appliquees",
      "Ecole pour l'Informatique et les nouvelles Technologies",
      "Ecole pour les Etudes et la Recherche en Informatique et Electronique",
      "Edge Hill University",
      "Eindhoven University of Technology",
      "Emory University",
      "Erasmus University Rotterdam",
      "Escuela Superior de Gestion Comercial y Marketing (ESIC)",
      "European Business School",
      "European Management Center Paris",
      "European Open University",
      "European School of Economics",
      "Falmouth University",
      "Fontys University of Applied Sciences",
      "Foundation University",
      "Futureworks",
      "Georgetown University",
      "Georgia Institute of Technology",
      "Glasgow Caledonian University",
      "Glasgow School of Art",
      "Global Business School Barcelona",
      "Goldsmiths College, University of London",
      "Grenoble Ecole de Management",
      "Groupe Sup de Co Amiens Picardie",
      "Groupe Sup de Co Montpellier",
      "Hanze University Groningen",
      "Harvard University",
      "Heriot-Watt University",
      "Heythrop College, University of London",
      "Hogeschool Inholland",
      "Hogeschool Leiden",
      "Hogeschool Rotterdam",
      "Hogeschool Utrecht",
      "Hogeschool van Amsterdam",
      "Hogeschool voor de Kunsten Utrecht (HKU)",
      "Hotelschool The Hague",
      "Huron University USA in London",
      "IDRAC (Institut de recherche en action commerciale)",
      "IE University",
      "IESE Business School",
      "IMT Atlantique",
      "INSEAD",
      "Imperial College London",
      "Imperial College School of Medicine",
      "Iniciativa Universidad del Atlantico",
      "Institue of Historical Research, University of London",
      "Institut Catholique d'Arts et Métiers Lille",
      "Institut Catholique de Paris",
      "Institut Catholique de Toulouse",
      "Institut Commercial de Nancy",
      "Institut National Polytechnique de Lorraine",
      "Institut National Polytechnique de Toulouse",
      "Institut National des Sciences Appliquées de Lyon",
      "Institut National des Sciences Appliquées de Rennes",
      "Institut National des Sciences Appliquées de Rouen",
      "Institut National des Sciences Appliquées de Toulouse",
      "Institut National des Télécommunications",
      "Institut Sup'Biotech de Paris",
      "Institut Supérieur Agricole de Beauvais",
      "Institut Supérieur d'Agriculture Lille",
      "Institut Supérieur d'Agriculture Rhone-Alpes",
      "Institut Supérieure d'Electronique de Paris",
      "Institut Supérieure d'Electronique du Nord",
      "Institut Textile et Chimique de Lyon",
      "Institut d'Etudes Politiques de Bordeaux",
      "Institut d'Etudes Politiques de Paris (Sciences Po)",
      "Institut d'études politiques de Rennes",
      "Institut de Recherche et Coordination Acoustique/Musique",
      "Institut de Recherche et d'Enseignement Supérieur aux Techniques de l'électronique",
      "Institut des Sciences de l'Ingénieur de Clermont-Ferrand",
      "Institut des Sciences de l'Ingénieur de Montpellier",
      "Institut des Sciences de la Matière et du Rayonnement",
      "Institut des hautes études économiques et commerciales",
      "Institut polytechnique de Grenoble",
      "Institut polytechnique des sciences avancees",
      "Institut privé d'enseignement supérieur",
      "Institute of Education, University of London",
      "Institute of Social Studies",
      "International Centre for Isclamic Science",
      "International Colleges of Islamic Science",
      "International Institute for Geo - Information Science and Earth Observation",
      "International University School of Medicine (IUSOM)",
      "International University of Southern Europe",
      "Islamic University of Rotterdam",
      "IÉSEG School of Management",
      "Johns Hopkins University",
      "Keele University",
      "King's College London, University of London",
      "Kingston University",
      "La Salle - Universitat Rámon Llull",
      "La Salle Universities - International Programmes",
      "Leeds Beckett University",
      "Leeds Trinity University",
      "Liverpool Hope University College",
      "Liverpool John Moores University",
      "London Business School",
      "London College of Science & Technology",
      "London Guildhall University",
      "London Institute of Management and Technology",
      "London Interdisciplinary School",
      "London Metropolitan University",
      "London School of Business & Finance",
      "London School of Economics and Political Science, University of London",
      "London School of Hygiene & Tropical Medicine, University of London",
      "London School of Jewish Studies",
      "Loughborough University",
      "Maastricht University",
      "Massachusetts Institute of Technology",
      "Michigan State University",
      "Middlesbrough College",
      "Middlesex University - London",
      "Mondragon Univertsitatea",
      "NHTV Breda University of Professional Education",
      "Napier University",
      "New York University",
      "Newcastle University",
      "Newport International University",
      "Northumbria University",
      "Northwestern University",
      "Nottingham Trent University",
      "Nyenrode Business University",
      "Ohio State University",
      "Open University",
      "Open University of the Netherlands",
      "Oxford Brookes University",
      "Penn State",
      "Princeton University",
      "Purdue University West Lafayette",
      "Queen Mary, University of London",
      "Radboud University",
      "Rennes School of Business",
      "Rice University",
      "Richmond University - The American International University in London",
      "Roehampton University of Surrey",
      "Roosevelt Academy University College",
      "Rotterdam School of Management",
      "Royal Academy of Music, University of London",
      "Royal College of Art",
      "Royal College of Music, University of London",
      "Royal Free Hospital School of Medicine, University of London",
      "Royal Holloway University of London",
      "Royal Holloway and Bedford New College",
      "SKEMA Business School",
      "Saint George's Hospital Medical School, University of London",
      "Saxion Universities",
      "Schiller International University, London",
      "Schiller International University, Madrid",
      "Schiller International University, Paris",
      "Schiller International University, Strasbourg",
      "School of Advanced Study, University of London",
      "School of Oriental and African Studies, University of London",
      "School of Pharmacy, University of London",
      "School of Slavonic and East European Studies, University of London",
      "Sheffield Hallam University",
      "Sorbonne Université - Faculté des Sciences (Paris VI)",
      "South Bank University",
      "Southampton Solent University",
      "St Mary's University",
      "St.James's School of Medicine, Bonaire",
      "St.Patrick's International College, London",
      "Staffordshire University",
      "Stanford University",
      "Stenden University",
      "Stratford College London",
      "Swansea Metropolitan University",
      "Swansea University",
      "Texas A&M University",
      "Thames Valley University",
      "The American University in London",
      "The Manchester Metropolitan University",
      "The Queen's University Belfast",
      "The Robert Gordon University",
      "The University of Chicago",
      "The University of Sheffield",
      "Tilburg University",
      "Trinity College Carmarthen",
      "Trinity College of Music",
      "Tufts University",
      "UNESCO-IHE Institute for Water Education",
      "Ulster University",
      "United Medical and Dental Schools, University of London",
      "Universidad Abierta Interactiva",
      "Universidad Alfonso X El Sabio",
      "Universidad Antonio de Nebrija",
      "Universidad Autónoma de Madrid",
      "Universidad Cardenal Herrera-CEU",
      "Universidad Carlos III de Madrid",
      "Universidad Católica San Antonio",
      "Universidad Católica de Valencia",
      "Universidad Católica de Ávila",
      "Universidad Complutense de Madrid",
      "Universidad Europea de Madrid",
      "Universidad Francisco de Vitoria",
      "Universidad Internacional Isabel I",
      "Universidad Internacional Menéndez Pelayo",
      "Universidad Internacional de Andalucía",
      "Universidad Internacional de Andalucía, Sede Antonio Machado de Baeza",
      "Universidad Internacional de Andalucía, Sede La Rábida",
      "Universidad Internacional de Valencia",
      "Universidad Loyola Andalucía",
      "Universidad Miguel Hernández de Elche",
      "Universidad Nacional de Educación a Distancia",
      "Universidad Pablo de Olavide",
      "Universidad Politécnica de Cartagena",
      "Universidad Politécnica de Cataluna",
      "Universidad Politécnica de Madrid",
      "Universidad Politécnica de Valencia",
      "Universidad Pontificia Comillas",
      "Universidad Pontificia de Salamanca",
      "Universidad Pública de Navarra",
      "Universidad Rey Juan Carlos",
      "Universidad de Alcalá de Henares",
      "Universidad de Alicante",
      "Universidad de Almería",
      "Universidad de Burgos",
      "Universidad de Cantabria",
      "Universidad de Castilla La Mancha",
      "Universidad de Cádiz",
      "Universidad de Córdoba",
      "Universidad de Deusto",
      "Universidad de Extremadura",
      "Universidad de Gerona",
      "Universidad de Granada",
      "Universidad de Huelva",
      "Universidad de Jaén",
      "Universidad de La Coruña",
      "Universidad de La Laguna",
      "Universidad de La Rioja",
      "Universidad de Las Palmas de Gran Canaria",
      "Universidad de León",
      "Universidad de Murcia",
      "Universidad de Málaga",
      "Universidad de Navarra",
      "Universidad de Oviedo",
      "Universidad de Salamanca",
      "Universidad de San Pablo CEU",
      "Universidad de Santiago de Compostela",
      "Universidad de Sevilla",
      "Universidad de Valencia",
      "Universidad de Valladolid",
      "Universidad de Vigo",
      "Universidad de Zaragoza",
      "Universidad del País Vasco",
      "Universitat Autónoma de Barcelona",
      "Universitat Internacional de Catalunya",
      "Universitat Jaume I de Castellón",
      "Universitat Oberta de Catalunya",
      "Universitat Pompeu Fabra",
      "Universitat Rovira I Virgili Tarragona",
      "Universitat Rámon Llull",
      "Universitat de Barcelona",
      "Universitat de Lleida",
      "Universitat de Vic",
      "Universitat de les Illes Balears",
      "Universiteit Leiden",
      "University Campus Suffolk",
      "University College London, University of London",
      "University for Humanistics (UH)",
      "University of Aberdeen",
      "University of Abertay Dundee",
      "University of Amsterdam",
      "University of Arizona",
      "University of Barcelona",
      "University of Bath",
      "University of Bath",
      "University of Bedfordshire",
      "University of Birmingham",
      "University of Bolton",
      "University of Bradford",
      "University of Brighton",
      "University of Bristol",
      "University of Buckingham",
      "University of Burgundy",
      "University of California",
      "University of California",
      "University of California",
      "University of Cambridge",
      "University of Central Lancashire",
      "University of Chester",
      "University of Colorado Boulder",
      "University of Derby",
      "University of Dundee",
      "University of Durham",
      "University of East Anglia",
      "University of East London",
      "University of Edinburgh",
      "University of Essex",
      "University of Exeter",
      "University of Florida",
      "University of Girona",
      "University of Glamorgan",
      "University of Glasgow",
      "University of Gloucestershire",
      "University of Greenwich",
      "University of Groningen",
      "University of Halifax, Birmingham Campus",
      "University of Hertfordshire",
      "University of Huddersfield",
      "University of Hull",
      "University of Illinois",
      "University of Kent at Canterbury",
      "University of Lancaster",
      "University of Leeds",
      "University of Leicester",
      "University of Lincoln",
      "University of Liverpool",
      "University of London",
      "University of Manchester",
      "University of Maryland",
      "University of Massachusetts",
      "University of Michigan-Ann Arbor",
      "University of Minnesota",
      "University of North London",
      "University of Northampton",
      "University of Nottingham",
      "University of Oxford",
      "University of Paisley",
      "University of Pennsylvania",
      "University of Pittsburgh",
      "University of Plymouth",
      "University of Portsmouth",
      "University of Portsmouth",
      "University of Reading",
      "University of Rochester",
      "University of Salford",
      "University of Sint Eustatius School of Medicine",
      "University of Southampton",
      "University of St. Andrews",
      "University of Stirling",
      "University of Strathclyde",
      "University of Sunderland",
      "University of Surrey",
      "University of Sussex",
      "University of Teesside",
      "University of Texas",
      "University of Twente",
      "University of Ulster",
      "University of Virginia",
      "University of Wales",
      "University of Wales College of Medicine",
      "University of Wales Institute, Cardiff",
      "University of Wales, Bangor",
      "University of Wales, Lampeter",
      "University of Wales, Newport",
      "University of Wales, Swansea",
      "University of Warwick",
      "University of Washington",
      "University of Westminster",
      "University of Wisconsin-Madison",
      "University of Wolverhampton",
      "University of Worcester",
      "University of York",
      "University of the Arts London",
      "University of the Netherlands Antilles, Curacao",
      "University of the West of England, Bristol",
      "Université Blaise Pascal (Clermont-Ferrand II)",
      "Université Bordeaux I",
      "Université Bourgogne - Franche-Comté",
      "Université Catholique de Lille",
      "Université Catholique de Lyon",
      "Université Catholique de l' Ouest",
      "Université Charles-de-Gaulle (Lille III)",
      "Université Claude Bernard (Lyon I)",
      "Université Clermont Auvergne",
      "Université Denis Diderot (Paris VII)",
      "Université François Rabelais de Tours",
      "Université Grenoble Alpes",
      "Université Henri Poincaré (Nancy I)",
      "Université Jean Monnet",
      "Université Jean Moulin (Lyon III)",
      "Université Louis Pasteur (Strasbourg I)",
      "Université Lumiére (Lyon II)",
      "Université Michel de Montaigne (Bordeaux III )",
      "Université Montesquieu (Bordeaux IV)",
      "Université Nancy II",
      "Université Panthéon-Assas (Paris II)",
      "Université Panthéon-Sorbonne (Paris I)",
      "Université Paris Nanterre (Paris X)",
      "Université Paris Nord (Paris XIII)",
      "Université Paris Sud (Paris XI)",
      "Université Paris-Dauphine (Paris IX)",
      "Université Paris-Est Marne-la-Vallée",
      "Université Paris-Saclay",
      "Université Paris-Sorbonne (Paris IV)",
      "Université Paul Sabatier (Toulouse III)",
      "Université Paul Valéry (Montpellier III)",
      "Université Rennes I",
      "Université Rennes II - Haute-Bretagne",
      "Université René Descartes (Paris V)",
      "Université Robert Schuman (Strasbourg III)",
      "Université Sorbonne-Nouvelle (Paris III)",
      "Université Val-de-Marne (Paris XII)",
      "Université Victor Segalen (Bordeaux II)",
      "Université Vincennes Saint-Denis (Paris VIII)",
      "Université d'Aix-Marseille",
      "Université d'Aix-Marseille III",
      "Université d'Angers",
      "Université d'Artois",
      "Université d'Auvergne (Clermont-Ferrand I)",
      "Université d'Avignon",
      "Université d'Evry Val d'Essonne",
      "Université d'Orléans",
      "Université de Bretagne Occidentale",
      "Université de Bretagne Sud",
      "Université de Caen Basse Normandie",
      "Université de Cergy-Pontoise",
      "Université de Corse Pascal Paoli",
      "Université de Haute-Alsace",
      "Université de La Rochelle",
      "Université de Limoges",
      "Université de Lorraine",
      "Université de Metz",
      "Université de Montpellier I",
      "Université de Montpellier II",
      "Université de Nantes",
      "Université de Nice-Sophia Antipolis",
      "Université de Pau et des Pays de l'Adour",
      "Université de Perpignan",
      "Université de Picardie Jules-Verne",
      "Université de Poitiers",
      "Université de Provence (Aix-Marseille I)",
      "Université de Reims Champagne-Ardenne",
      "Université de Rouen - Haute Normandie",
      "Université de Savoie",
      "Université de Strasbourg",
      "Université de Technologie de Belfort Montbéliard",
      "Université de Technologie de Compiègne",
      "Université de Technologie de Troyes",
      "Université de Toulouse",
      "Université de Toulouse-le-Mirail (Toulouse II)",
      "Université de Valenciennes et du Hainaut-Cambrésis",
      "Université de Versailles Saint-Quentin-en-Yvelines",
      "Université de la Méditerranée (Aix Marseille II)",
      "Université des Sciences Humaines (Strasbourg II)",
      "Université des Sciences Sociales (Toulouse I)",
      "Université des Sciences et Technologies de Lille (Lille I)",
      "Université du Droit et de la Sante (Lille II)",
      "Université du Havre",
      "Université du Littoral Cote d'Opale",
      "Université du Maine",
      "Université du Sud, Toulon et Var",
      "Utrecht University",
      "Vanderbilt University",
      "Vrije Universiteit Amsterdam",
      "Wageningen University",
      "Wakefield College",
      "Warnborough University",
      "William Gilbert College",
      "Wimbledon School of Art",
      "Wittenborg University",
      "Yale University",
      "York St. John University",
      "Zuyd University",
      "ifs University College",
      "École Polytechnique",
      "École des Hautes Études Commerciales (HEC Business School)"
    ]
end
